### ISSUE TITLE
Palm Rejection missing?

### ISSUE THREAD

**Issue by kskim7** [kushwavez/lenovo-x1c6-clover-efi#1] opened 2021-02-14 07:40 UTC
Hi Kushwavez, thanks for the updated EFI's.
I've been using your EFI's for my X1C6 very usefully.
I've commented on your redddit post, perhaps you might remember me commenting on trackpoint scrolling.
This time with your new EFI's the scroll issue is perfectly gone,
but this time, palm rejection seems to be gone too.
Without palm rejection it's very difficult to type. 
Do you not have this issue?

One more thing, in your previous EFI's sleep-hibernation worked smoothly.
But this new EFI has trouble with sleep issue. It becomes volcano hot in my backpack.
How about your carbon? Is it the same??

**Comment by kushwavez** [comment] 2021-02-14 07:53
**About VoodooRMI:** I had problems with palm rejection on v1.3.1, so I reverted back to v1.2, also reported the issues to the dev so I think that should be okay in the next release. 
This version doesn't have palm rejection. If you need that, download the 1.3.1 VoodooRMI and use that. 

**About sleep/hibernation:** Are you hibernating or put it to sleep? I didn't really test hibernation, so I have to look into it. Sleep is working fine on my side. 
You have to disable Power Nap in System Preferences -> Battery -> Battery, and Power Adapter

**Comment by kskim7** [comment] 2021-02-15 05:18
Thanks, palm rejection issue is solved by replacing VoodooRMI and VoodooSMBUS with v.1.3.1.
And sleep, it's just sleep, not hibernation. Give me some days to test on this issue. Last time when the issue appeared, I didn't actually test it.

Oh, btw, your SMBIOS is using MacBookPro15,2 while others are using 14,1. Is serial number validation not a problem with yours? Mine seems to not work (tested 20-some serial numbers generated with GenSMBIOS).

**Comment by kushwavez** [comment] 2021-02-15 07:10
Ah yes, my bad. I actually thought that this SMBIOS is the best for our CPU, but ours are Kaby Lake-R and MBP 15,2 is Coffee Lake. I'll change to MBP14,1. 

But the problem is not with that, the change won't make any significant changes. 

Btw what do you mean by validate? You can't sign into iCloud services? 
Also I didn't use GenSMBIOS. I generated the SMBIOS inside Clover Configurator -> SMBIOS. I use that every time, doesn't have any problems, I'm logged in on all iServices. 
For note: try to not change your SMBIOS all the time. Generate one with Clover, if working then use that so on. 

Now I'm closing this issue, but we can still discuss these.

**Closed as completed by kushwavez** 2021-02-15 07:10 UTC
Labels: question

**Comment by kushwavez** [comment] 2021-02-15 07:55
Okay, I changed to MBP14,1 SMBIOS now. 
- Simply logged out from iCloud before
- changed SMBIOS to MBP14,1 in Clover Configurator -> SMBIOS (simply selected MBP14,1 from the drop-down list)
- Restart with new SMBIOS
- Login to iCloud. 

that's it, it's now synchronising my data.

And I noticed something: with this SMBIOS we don't have HDR option in Safari, YouTube anymore. 
Well, doesn't really matter, the screen is not HDR.

**Comment by kskim7** [comment] 2021-02-15 08:31
Good, what I did with SMBIOS is, as the others said in their guides, after changing the serial number, I went to the Apple’s warranty status and eligibility page, where we can check whether the number is valid or not. 

https://checkcoverage.apple.com/us/en

There I tried to find the number that’s actually working, but I previously failed to do that with your macbookpro15,2 smbios.
But changing to 14,1 will solve this problem since I have the number that’s actually working.

and.. HDR?? I’m thinking of changing my LCD panel to a WQHD panel with HDR in the near future. Maybe I’ll have to figure out ways to use 15,2 smbios for HDR by then.

anyway, big thanks bro!!

**Comment by kushwavez** [comment] 2021-02-15 08:55
> Good, what I did with SMBIOS is, as the others said in their guides, after changing the serial number, I went to the Apple’s warranty status and eligibility page, where we can check whether the number is valid or not.
> 
> https://checkcoverage.apple.com/us/en

I didn't know about this, I never ever in my life used this method. I simply used this Clover (and OC), SMBIOS gen since Sierra 10.12, and generated a lots of SMBIOSes. I even use the same generated SMBIOS on OC too, to not confuse iCloud. 
I also thought  a generated SMBIOS is not supposed to be valid in the first place.

I suppose it's in the dortania's guide, yes? I'll read it and try to understand why it is suggesting this, thanks. 

> and.. HDR?? I’m thinking of changing my LCD panel to a WQHD panel with HDR in the near future. Maybe I’ll have to figure out ways to use 15,2 smbios for HDR by then.

Yes I'm thinking of the same thing as well. As I said it's just a simple SMBIOS generate, supposed to work. I used MBP15,2 since I got this notebook.

I'll test with this SMBIOS for more time, and if I won't see any changes I'll change it back to MBP15,2. As far as I can see, there aren't any changes whatsoever (except the no HDR option)

**Comment by kushwavez** [comment] 2021-02-15 09:21
> Good, what I did with SMBIOS is, as the others said in their guides, after changing the serial number, I went to the Apple’s warranty status and eligibility page, where we can check whether the number is valid or not.
> 
>  https://checkcoverage.apple.com/us/en

Okay I read dortania's guide. But I think it's still not needed as it's working just fine with simply generating inside Clover Configurator or OpenCore Configurator. 

I just generated a new MBP15,2 to see if there are any changes whatsoever.
Logged out from iCloud
changed to MBP15,2
restart, reset NVRAM with F11 in Clover, restart, logged in
-> iCloud started syncing
-> HDR is working again
No other changes

So as far as I can see, MBP15,2 should be okay, we also get HDR for YouTube, so why not.

**Comment by kskim7** [comment] 2021-02-16 02:02
Thanks for everything you did to answer my questions. 
Your “So why not” sounds so compelling.
I’m gonna stick to 15,2 just as you did. 
thanks!!!
